sources:
  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment
  - name: jaffle_shop
    database: til_portfolio_projects
    schema: jaffle_shop
    tables:
      - name: orders
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: _etl_loaded_at
      - name: customers